function com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo(){var U='',Cb='" for "gwt:onLoadErrorFn"',Ab='" for "gwt:onPropertyErrorFn"',nb='"><\/script>',cb='#',Kb='&',vc='.cache.html',eb='/',qb='//',hc='3326AA24BBD0F14196E27E253DA467D2',jc='460EDA8BE6297D98F26BCFC3031A05BC',kc='495B338170E9113869C84F52B28DC3B9',lc='56C3DAD4F352C75D960B17622EA4A973',mc='6F377622FA3934A62A172D98B32E2F52',nc='70C9AA8E33171764AC1323B707DDB581',oc='721693CEAF9D54BA53817DF3953AD625',pc='9D6CB1933954552F29B06738652F1D66',uc=':',ic=':1',ub='::',Fc='<script defer="defer">com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo.onInjectionDone(\'com.tractionsoftware.gwt.demo.utcdatetime.UTCDateTimeDemo\')<\/script>',mb='<script id="',xb='=',db='?',zb='Bad handler "',qc='D93520834E6111CF766001A90027B527',rc='DA498FF050138F824EF2EB865250D66C',Ec='DOMContentLoaded',sc='E3E614D6CB3F84CF68CA79120BCBB6BD',tc='F20602A292F3EC3B6DD1B0D7FBB68724',ob='SCRIPT',Nb='Unexpected exception in locale detection, using default: ',Mb='_',Lb='__gwt_Locale',lb='__gwt_marker_com.tractionsoftware.gwt.demo.utcdatetime.UTCDateTimeDemo',pb='base',hb='baseUrl',Y='begin',X='bootstrap',gb='clear.cache.gif',V='com.tractionsoftware.gwt.demo.utcdatetime.UTCDateTimeDemo',jb='com.tractionsoftware.gwt.demo.utcdatetime.UTCDateTimeDemo.nocache.js',tb='com.tractionsoftware.gwt.demo.utcdatetime.UTCDateTimeDemo::',wb='content',Rb='datetime',Ib='default',Dc='demo.css',gc='en',bb='end',ac='gecko',bc='gecko1_8',Z='gwt.codesvr=',$='gwt.hosted=',_='gwt.hybrid',Cc='gwt/standard/standard.css',Bb='gwt:onLoadErrorFn',yb='gwt:onPropertyErrorFn',vb='gwt:property',Bc='head',ec='hosted.html?com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo',Ac='href',Zb='ie10',_b='ie8',$b='ie9',Db='iframe',fb='img',Pb='input',Eb="javascript:''",xc='link',dc='loadExternalRefs',Hb='locale',Jb='locale=',rb='meta',Gb='moduleRequested',ab='moduleStartup',Yb='msie',Ub='n',sb='name',Fb='position:absolute;width:0;height:0;border:none',yc='rel',Xb='safari',ib='script',fc='selectingPermutation',W='startup',zc='stylesheet',Ob='supportsDateTimeInput',Sb='text',wc='timebox.css',Qb='type',kb='undefined',cc='unknown',Vb='user.agent',Wb='webkit',Tb='y';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=U,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:Y});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Z)!=-1||(c.indexOf($)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(_)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(V);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return M(a)}}com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo=null;c.gwtOnLoad(C,V,t,B);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:bb})}}
function H(){function e(a){var b=a.lastIndexOf(cb);if(b==-1){b=a.length}var c=a.indexOf(db);if(c==-1){c=a.length}var d=a.lastIndexOf(eb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(fb);b.src=a+gb;a=e(b.src)}return a}
function g(){var a=K(hb);if(a!=null){return a}return U}
function h(){var a=n.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(jb)!=-1){return e(a[b].src)}}return U}
function i(){var a;if(typeof isBodyLoaded==kb||!isBodyLoaded()){var b=lb;var c;n.write(mb+b+nb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ob){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return U}
function j(){var a=n.getElementsByTagName(pb);if(a.length>0){return a[a.length-1].href}return U}
function k(){var a=n.location;return a.href==a.protocol+qb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==U){l=h()}if(l==U){l=i()}if(l==U){l=j()}if(l==U&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(rb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(sb),g;if(f){f=f.replace(tb,U);if(f.indexOf(ub)>=0){continue}if(f==vb){g=e.getAttribute(wb);if(g){var h,i=g.indexOf(xb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=U}u[f]=h}}else if(f==yb){g=e.getAttribute(wb);if(g){try{D=eval(g)}catch(a){alert(zb+g+Ab)}}}else if(f==Bb){g=e.getAttribute(wb);if(g){try{C=eval(g)}catch(a){alert(zb+g+Cb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function M(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var N;function O(){if(!N){N=true;var a=n.createElement(Db);a.src=Eb;a.id=V;a.style.cssText=Fb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:Gb});a.contentWindow.location.replace(t+Q)}}
w[Hb]=function(){var b=null;var c=Ib;try{if(!b){var d=location.search;var e=d.indexOf(Jb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Kb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=K(Hb)}if(!b){b=m[Lb]}if(b){c=b}while(b&&!J(Hb,b)){var h=b.lastIndexOf(Mb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Nb+a)}m[Lb]=c;return b||Ib};v[Hb]={'default':0,en:1};w[Ob]=function(){try{var b=document.createElement(Pb);b.setAttribute(Qb,Rb);return b.type!==Sb?Tb:Ub}catch(a){return Ub}};v[Ob]={n:0,y:1};w[Vb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Wb)!=-1}())return Xb;if(function(){return b.indexOf(Yb)!=-1&&n.documentMode>=10}())return Zb;if(function(){return b.indexOf(Yb)!=-1&&n.documentMode>=9}())return $b;if(function(){return b.indexOf(Yb)!=-1&&n.documentMode>=8}())return _b;if(function(){return b.indexOf(ac)!=-1}())return bc;return cc};v[Vb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo.onScriptLoad=function(){if(N){r=true;G()}};com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo.onInjectionDone=function(){q=true;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:dc,millis:(new Date).getTime(),type:bb});G()};I();H();var P;var Q;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(V))){m.location.reload();return}Q=ec;P=U}o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:fc});if(!F()){try{L([gc,Ub,Zb],hc);L([gc,Tb,Zb],hc);L([gc,Ub,Zb],hc+ic);L([gc,Tb,Zb],hc+ic);L([gc,Ub,bc],jc);L([gc,Tb,bc],jc);L([gc,Ub,bc],jc+ic);L([gc,Tb,bc],jc+ic);L([gc,Ub,Xb],kc);L([Ib,Ub,Xb],lc);L([Ib,Tb,Xb],mc);L([Ib,Ub,Zb],nc);L([Ib,Tb,Zb],nc);L([Ib,Ub,Zb],nc+ic);L([Ib,Tb,Zb],nc+ic);L([gc,Ub,_b],oc);L([gc,Tb,_b],oc);L([gc,Ub,_b],oc+ic);L([gc,Tb,_b],oc+ic);L([gc,Tb,Xb],pc);L([Ib,Ub,_b],qc);L([Ib,Tb,_b],qc);L([Ib,Ub,_b],qc+ic);L([Ib,Tb,_b],qc+ic);L([Ib,Ub,bc],rc);L([Ib,Tb,bc],rc);L([Ib,Ub,bc],rc+ic);L([Ib,Tb,bc],rc+ic);L([gc,Ub,$b],sc);L([gc,Tb,$b],sc);L([gc,Ub,$b],sc+ic);L([gc,Tb,$b],sc+ic);L([Ib,Ub,$b],tc);L([Ib,Tb,$b],tc);L([Ib,Ub,$b],tc+ic);L([Ib,Tb,$b],tc+ic);P=A[M(Hb)][M(Ob)][M(Vb)];var R=P.indexOf(uc);if(R!=-1){B=Number(P.substring(R+1));P=P.substring(0,R)}Q=P+vc}catch(a){return}}var S;function T(){if(!s){s=true;if(!__gwt_stylesLoaded[wc]){var a=n.createElement(xc);__gwt_stylesLoaded[wc]=a;a.setAttribute(yc,zc);a.setAttribute(Ac,t+wc);n.getElementsByTagName(Bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Cc]){var a=n.createElement(xc);__gwt_stylesLoaded[Cc]=a;a.setAttribute(yc,zc);a.setAttribute(Ac,t+Cc);n.getElementsByTagName(Bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Dc]){var a=n.createElement(xc);__gwt_stylesLoaded[Dc]=a;a.setAttribute(yc,zc);a.setAttribute(Ac,t+Dc);n.getElementsByTagName(Bc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Ec,T,false)}if(S){clearInterval(S)}}}
if(n.addEventListener){n.addEventListener(Ec,function(){O();T()},false)}var S=setInterval(function(){if(/loaded|complete/.test(n.readyState)){O();T()}},50);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:bb});o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:dc,millis:(new Date).getTime(),type:Y});n.write(Fc)}
com_tractionsoftware_gwt_demo_utcdatetime_UTCDateTimeDemo();